//Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

//check sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

//comment
export const COMMENT_POST = "COMMENT_POST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";

export const COMMENT_EDIT = "COMMENT_EDIT";
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS";
export const COMMENT_EDIT_FAILURE = "COMMENT_EDIT_FAILURE";

export const COMMENT_LIST = "COMMENT_LIST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILURE = "COMMENT_LIST_FAILURE";

export const COMMENT_REMOVE = "COMMENT_REMOVE";
export const COMMENT_REMOVE_SUCCESS = "COMMENT_REMOVE_SUCCESS";
export const COMMENT_REMOVE_FAILURE = "COMMENT_REMOVE_FAILURE";